In [6]:
import numpy as np

In [ ]:
#1.3.2.1

In [7]:
a = np.array([1,2,3,4])
print(a)
print(a+1)
print(2**a)

[1 2 3 4]
[2 3 4 5]
[ 2  4  8 16]


In [11]:
b = np.ones(4) + 1
print(a - b)
print(a*b)
j = np.arange(5)
print(j)
print(2**(j + 1) - j)

[-1.  0.  1.  2.]
[2. 4. 6. 8.]
[0 1 2 3 4]
[ 2  3  6 13 28]


In [14]:
a = np.arange(10000)
%timeit a + 1
l = range(10000)
%timeit [i+1 for i in l]

24.6 µs ± 553 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
2.57 ms ± 51.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
c = np.ones((3,3))
print(c*c)
print(c.dot(c))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [24]:
def Jumlah(mix):
    ev_li = []
    od_li = []
    for i in mix:
        if (i%2 == 0):
            ev_li.append(i)
        else:
            od_li.append(i)
    print(od_li + ev_li)

a = np.arange(20) + 2
Jumlah(a)


[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
None


In [27]:
a = np.triu(np.ones((3,3)),1)
print(a)
print(a.T)

[[0. 1. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]]


In [30]:
#1.3.2.2
x = np.array([1, 2, 3, 4])
print(x.sum())
print(np.sum(x))

10
10


In [31]:
x = np.array([1, 3, 2])
print(x.min())
print(x.max())
print(x.argmin())
print(x.argmax())

1
3
0
1


In [33]:
print(np.all([True, True, False]))
print(np.any([True,True,False]))

False
True


In [34]:
x = np.array([1, 2, 3, 1])
y = np.array([[1,2,3],[5,6,1]])
print(x.mean())
print(np.median(x))
print(np.median(y, axis = -1))
print(x.std())

1.75
1.5
[2. 5.]
0.82915619758885


In [41]:
#1.3.2.3. Broadcasting
#conversion to make arrays have same size
a = np.tile(np.arange(0, 40, 10), (2,1)).T
print(a)
b = np.array([0,1])
print(a+b)

[[ 0  0]
 [10 10]
 [20 20]
 [30 30]]
[[ 0  1]
 [10 11]
 [20 21]
 [30 31]]


In [46]:
#1.3.2.4
#Array shape manipulation
#flattening
a = np.array([[1,2,3],[4,5,6]])
print(a.ravel())
print(a.T)
print(a.T.ravel())
#reshape
print(a.shape)
b = a.ravel()
b = b.reshape((2,3))
print(b)

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[1 4 2 5 3 6]
(2, 3)
[[1 2 3]
 [4 5 6]]


In [61]:
#1.3.2.5
#Sorting
a = np.array([[4,3,5],[11,31,20]])
b = np.sort(a,axis = 1)
print(b)
a.sort(axis=1)
print(a)

[[ 3  4  5]
 [11 20 31]]
[[ 3  4  5]
 [11 20 31]]
